os: linux
language: cpp
compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install cmake libboost-all-dev
 - pip install --user cpp-coveralls

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov

before_script:
 - mkdir build
 - cd build
 - cmake -DBUILD_TESTS=ON ..

script:
  - make 
  - make test

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '*/usr/*' --output-file coverage.info # filter out system
  - lcov --remove coverage.info '*/boost*/*' --output-file coverage.info
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'