version: 1.0.{build}
environment:
  PATH: '%PATH%;C:\MinGW\bin'
  BOOST_ROOT: C:\Libraries\boost_1_63_0
build_script:
- cmd: "cmake CMakeLists.txt \ncmake --build ."
artifacts:
- path: Debug\Steganifyer.exe
  name: Steganifyer.exe
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true